### ISSUE TITLE
Crash after Resuming 

### ISSUE THREAD

**Issue by ryloc** [cplaverty/KeitaiWaniKani#15]
Often when the user launches the app after using it previously, the splash screen with hang for a few seconds, and then quit. After this the app launches normally. 

Device: iPhone X, 11.3

**Comment by cplaverty** [comment]
Sorry for the delay in responding.  As far as I can tell, this issue comes about in the App Store version of the app when it tries to schedule the review notifications.  That version of the app is using a deprecated version of the local notifications API.  This notification code has been rewritten in the current version (3.0), and will no longer be an issue when it's released.

**Comment by ryloc** [comment]
Oh! Thanks for the reply - I appreciate it! If you need any testers for future versions let me know. Either way, looking forward to the update (and glad it still lives!) - it’s one of the few apps I constantly use. :)
On May 30, 2018, 12:38 PM -0700, Chris Laverty <notifications@github.com>, wrote:

Closed #15<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcplaverty%2FKeitaiWaniKani%2Fissues%2F15&data=02%7C01%7C%7Cd670d97fd1b24b29658208d5c664e44f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636633058980442055&sdata=WwczVzRs20Q0sCS9JZdL0eT4tss30877pS9BLAAPLYs%3D&reserved=0>.
