### ISSUE TITLE
2.0 iOS App Crashes on Start Up

### ISSUE THREAD

**Issue by aum9n** [cplaverty/KeitaiWaniKani#2]
iPhone 6 w/ iOS 9.3 Public Beta 3
iPhone 6 w/ iOS 9.2
iPad mini 3 w/ iOS 9.2

Crashes on start up. You can see a fraction of a second of updates and then it returns to the home screen. I have restarted all devices, and deleted and reinstalled the app on all devices. The login screen doesn't crash, but the moment you log in it crashes.

Notifications still work, but I'm not doing them via web instead of the app.

**Comment by cplaverty** [comment]
It's likely there's something unexpected in the data downloaded from the WaniKani API.  I would be very grateful if you could provide your API key for me to diagnose this.  It provides a read-only view of your data which I won't keep, and you can generate a new API key once I've diagnosed what the issue is.  Would you mind mailing it to me at allicrab@icloud.com?  You can find it in your account settings (https://www.wanikani.com/account) under "Public API Key".  Thanks!

**Comment by aum9n** [comment]
emailed. thanks!

**Comment by cplaverty** [comment]
Released beta version of 2.0.1 which fixes this issue.
