### ISSUE TITLE
Text cursor blinking before field appears

### ISSUE THREAD

**Issue by almercier** [cplaverty/KeitaiWaniKani#25]
Just a minor issue, but is it possible to clean up the UI during the loading of the review page? I'm seeing the cursor appear and blink before the page is fully displayed. I am also seeing it scroll down slightly on initial load, or when I close and reopen the app with the review page open. I understand that this will not be an issue after localized reviewing is done, but for now if it is a quick fix it may be worth it?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30079507/59105462-f2069100-8901-11e9-9b5f-0bf029290f72.gif)

**Comment by cplaverty** [comment]
The cursor blinking I don’t know of any way to work around. There’s nothing I’m doing here to give focus to that text field hidden behind the image, other than allowing the call to focus that text field to succeed where it would otherwise fail (otherwise you need to tap the field to open the keyboard).

And the page jumping has been an annoyance to me for years. I have spent many hours trying to find a fix for this, but it has eluded me.

**Comment by almercier** [comment]
I'll try pulling the repo and investigating myself to see if I can find anything.
