### ISSUE TITLE
New Features request

### ISSUE THREAD

**Issue by cbaidon45** [cplaverty/KeitaiWaniKani#9]
-wanikani statistics ( to track progress on goyo, jlpt, etc)
-search for kanji or radicals
-search for words in english
-view current items status in srs items distribution ( be able to view Guru, Apprentice items, like in the webpage)

Thanks

**Comment by turtlemaster19** [comment]
> -wanikani statistics ( to track progress on goyo, jlpt, etc)
That can be done at [WK Stats v2](https://wkstats.com:10001)
> -search for kanji or radicals
> -search for words in english
Both of these are somewhat implemented already.
> -view current items status in srs items distribution ( be able to view Guru, Apprentice items, like in the webpage)
That can also be done at [WK Stats v2](https://wkstats.com:10001)
> 
> Thanks

**Comment by cplaverty** [comment]
This issue is quite old now, so I don’t know if you’re still using WaniKani. In any case, I meant to reply to this issue when version 3 was released.

As others have noted, version 3 brought the ability to search using English or Japanese for meanings, readings or kanji. 

Tracking completion of kanji to Joyo or JLPT lists I am unlikely to add to the app. I will instead echo the recommend for rfindley’s excellent stats site. 

Item browsing (including listing by SRS stage) is still on my list to complete, so I was intending on leaving this issue open until that was done.

**Comment by cbaidon45** [comment]
Hi:

Yes, this issue is quite old i opened this issue when i was beginning to study kanji, nowadays i am in the last part of Genki II and on my way to take JLPT N4 in December. I think studying kanji is gonna become more and more from N3 and forwards. Nice to hear from you!

Cheers
